/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package booking;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Bookings extends javax.swing.JFrame {

    /**
     * Creates new form Bookings
     */
    public Bookings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Backbtn = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        subOne = new javax.swing.JButton();
        Adults = new javax.swing.JTextField();
        addOne = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        subOne1 = new javax.swing.JButton();
        addOne1 = new javax.swing.JButton();
        Children = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        checkin = new org.jdesktop.swingx.JXDatePicker();
        checkout = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 162, 232));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(24, 26, 28));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Backbtn.setBackground(new java.awt.Color(0, 162, 232));
        Backbtn.setFont(new java.awt.Font("Dotum", 1, 12)); // NOI18N
        Backbtn.setForeground(new java.awt.Color(255, 255, 255));
        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));

        Next.setBackground(new java.awt.Color(0, 162, 232));
        Next.setFont(new java.awt.Font("Dotum", 1, 12)); // NOI18N
        Next.setForeground(new java.awt.Color(255, 255, 255));
        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        jPanel2.add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking/check-in11.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel2.setBackground(new java.awt.Color(24, 26, 28));
        jLabel2.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CHECK-OUT");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking/check-out11.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel4.setBackground(new java.awt.Color(24, 26, 28));
        jLabel4.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CHECK-IN");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        subOne.setBackground(new java.awt.Color(24, 26, 28));
        subOne.setForeground(new java.awt.Color(24, 26, 28));
        subOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking/minus1.png"))); // NOI18N
        subOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subOneMouseClicked(evt);
            }
        });
        subOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subOneActionPerformed(evt);
            }
        });
        jPanel2.add(subOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 60, 70));

        Adults.setEditable(false);
        Adults.setBackground(new java.awt.Color(24, 26, 28));
        Adults.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        Adults.setForeground(new java.awt.Color(255, 255, 255));
        Adults.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Adults.setText("1");
        jPanel2.add(Adults, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 60, 50));

        addOne.setBackground(new java.awt.Color(24, 26, 28));
        addOne.setForeground(new java.awt.Color(24, 26, 28));
        addOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking/plus.png"))); // NOI18N
        addOne.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addOneMouseClicked(evt);
            }
        });
        addOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOneActionPerformed(evt);
            }
        });
        jPanel2.add(addOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 60, 70));

        jLabel5.setBackground(new java.awt.Color(24, 26, 28));
        jLabel5.setFont(new java.awt.Font("Dotum", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Adults");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 60, 20));

        subOne1.setBackground(new java.awt.Color(24, 26, 28));
        subOne1.setForeground(new java.awt.Color(24, 26, 28));
        subOne1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking/minus1.png"))); // NOI18N
        subOne1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        subOne1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subOne1MouseClicked(evt);
            }
        });
        jPanel2.add(subOne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 60, 70));

        addOne1.setBackground(new java.awt.Color(24, 26, 28));
        addOne1.setForeground(new java.awt.Color(24, 26, 28));
        addOne1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking/plus.png"))); // NOI18N
        addOne1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addOne1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addOne1MouseClicked(evt);
            }
        });
        addOne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOne1ActionPerformed(evt);
            }
        });
        jPanel2.add(addOne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 60, 70));

        Children.setEditable(false);
        Children.setBackground(new java.awt.Color(24, 26, 28));
        Children.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        Children.setForeground(new java.awt.Color(255, 255, 255));
        Children.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Children.setText("0");
        jPanel2.add(Children, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 60, 50));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Children");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 60, 20));

        checkin.setForeground(new java.awt.Color(255, 255, 255));
        checkin.setEditable(false);
        jPanel2.add(checkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        checkout.setForeground(new java.awt.Color(255, 255, 255));
        checkout.setEditable(false);
        jPanel2.add(checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 660, 500));

        jLabel7.setBackground(new java.awt.Color(0, 162, 232));
        jLabel7.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(24, 26, 28));
        jLabel7.setText("2/3  Reservations");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // TODO add your handling code here:
        Registration reg= new Registration();
        reg.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_BackbtnActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
        Choose_room choose= new Choose_room();
        choose.setVisible(true);
        dispose();
    }//GEN-LAST:event_NextActionPerformed

    private void addOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addOneActionPerformed

    private void subOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subOneActionPerformed

    private void addOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addOneMouseClicked
        // TODO add your handling code here:
        String strAdults= Adults.getText();
        int inAdults=Integer.parseInt(strAdults);
        if(evt.getSource()==addOne){
            if(inAdults<5){
                inAdults++;
                Adults.setText(""+inAdults);
            }else JOptionPane.showMessageDialog(rootPane, "Maximum number of Adults in a room is 5");
        }
    }//GEN-LAST:event_addOneMouseClicked

    private void subOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subOneMouseClicked
        // TODO add your handling code here:
        String strAdults1=Adults.getText();
        int inAdults1=Integer.parseInt(strAdults1);
        if (evt.getSource()==subOne){
            if(inAdults1>1){
                inAdults1--;
                Adults.setText(""+inAdults1);
            }else JOptionPane.showMessageDialog(rootPane, "There must be at least an adult in the room");
        }
    }//GEN-LAST:event_subOneMouseClicked

    private void addOne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOne1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addOne1ActionPerformed

    private void addOne1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addOne1MouseClicked
        // TODO add your handling code here:
        String strChildren= Children.getText();
        int inChildren=Integer.parseInt(strChildren);
        if (evt.getSource()==addOne1){
            if(inChildren<5){
                inChildren++;
                Children.setText(""+inChildren);
            }   else JOptionPane.showMessageDialog(rootPane, "Maximum number of Children in a room is 5");    
        }
    }//GEN-LAST:event_addOne1MouseClicked

    private void subOne1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subOne1MouseClicked
        // TODO add your handling code here:
        String strChildren1= Children.getText();
        int inChildren1=Integer.parseInt(strChildren1);
        if(evt.getSource()==subOne1);
            if(inChildren1>0){
             inChildren1--;
             Children.setText(""+inChildren1);
            }  
    }//GEN-LAST:event_subOne1MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bookings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Adults;
    private javax.swing.JButton Backbtn;
    private javax.swing.JTextField Children;
    private javax.swing.JButton Next;
    private javax.swing.JButton addOne;
    private javax.swing.JButton addOne1;
    private org.jdesktop.swingx.JXDatePicker checkin;
    private org.jdesktop.swingx.JXDatePicker checkout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton subOne;
    private javax.swing.JButton subOne1;
    // End of variables declaration//GEN-END:variables
}
