/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package booking;

import java.awt.Toolkit;

/**
 *
 * @author user
 */
public class Home extends javax.swing.JFrame {

    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        facebookContact = new javax.swing.JLabel();
        GmailContactt = new javax.swing.JLabel();
        twitterContact = new javax.swing.JLabel();
        instagramContact = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Akma Signatures Hotel");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 162, 232));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking/TowerImage.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel2.setBackground(new java.awt.Color(24, 26, 28));
        jLabel2.setFont(new java.awt.Font("Gabriola", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(24, 26, 28));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><i>.........Comfort redefined</i> Hotel</html>");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 220, 40));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 300, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 220, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 220, 0));

        jLabel11.setBackground(new java.awt.Color(24, 26, 28));
        jLabel11.setFont(new java.awt.Font("Gabriola", 1, 26)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(24, 26, 28));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("<html><i>Akma Signatures</i> Hotel</html>");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 220, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 470));

        jPanel2.setBackground(new java.awt.Color(24, 26, 28));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking/location-marker.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 300, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking/phone.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 300, 10));

        jButton1.setBackground(new java.awt.Color(0, 162, 232));
        jButton1.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BOOK NOW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 210, 50));

        facebookContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking/facebook (2).png"))); // NOI18N
        facebookContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facebookContactMouseClicked(evt);
            }
        });
        jPanel2.add(facebookContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        GmailContactt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking/gmail.png"))); // NOI18N
        GmailContactt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GmailContacttMouseClicked(evt);
            }
        });
        jPanel2.add(GmailContactt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 40, 50));

        twitterContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking/twitter.png"))); // NOI18N
        twitterContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twitterContactMouseClicked(evt);
            }
        });
        jPanel2.add(twitterContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        instagramContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking/instagram.png"))); // NOI18N
        instagramContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instagramContactMouseClicked(evt);
            }
        });
        jPanel2.add(instagramContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dotum", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("<html><p>No 3,Osuntokun Avenue,Bodija Ibadan<br/>Oyo State.</p></html>");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 260, 40));

        jLabel10.setFont(new java.awt.Font("Dotum", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("+234-813-371-5780");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 220, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking/akma1.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 190, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 390, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Registration reg= new Registration (this);
        reg.setLocationRelativeTo(null);
         reg.setVisible(true);
         this.setVisible(false);
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void facebookContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facebookContactMouseClicked
       BrowserLaunch.openURL("https://www.facebook.com/azeezayotunde");
    }//GEN-LAST:event_facebookContactMouseClicked

    private void twitterContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twitterContactMouseClicked
        BrowserLaunch.openURL("https://www.twitter.com");
    }//GEN-LAST:event_twitterContactMouseClicked

    private void instagramContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instagramContactMouseClicked
       BrowserLaunch.openURL("https://www.instagram.com/heyz_man");
    }//GEN-LAST:event_instagramContactMouseClicked

    private void GmailContacttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GmailContacttMouseClicked
       BrowserLaunch.openURL("https://mail.google.com/mail/?view=cm&fs=1&to=azeezco1@gmail.com&su=FEEDBACK&bcc=lawalazeez1111@gmail.com");
    }//GEN-LAST:event_GmailContacttMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                    Thread.sleep(4500);
                }catch(Exception e){}
               Home home= new Home();
               home.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GmailContactt;
    private javax.swing.JLabel facebookContact;
    private javax.swing.JLabel instagramContact;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel twitterContact;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("akmaicon.png")));
    }
}
