/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package booking;


import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author user
 */
public class Registration extends javax.swing.JFrame {
     
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public JFrame Home;
    public Boolean numberValidation(String num1){
        
        return num1.charAt(0)=='0' && (num1.charAt(1)=='7' || num1.charAt(1)=='8' || num1.charAt(1)=='9') && num1.length()==11 && num1.matches("[0-9]+");     }
    /**
     * Creates new form Registration
     */
    public Registration() {
        
        initComponents();
        setIcon();
       
            
    }
       public Registration(JFrame home) {
        Home=home;
        initComponents();
        setIcon();
        conn=DB_connect.connect_DB();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        Nextbtn = new javax.swing.JButton();
        Cancelbtn = new javax.swing.JButton();
        phone_no = new javax.swing.JTextField();
        kinNo = new javax.swing.JTextField();
        fullname = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        kin = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Akma Signatures Hotel");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 162, 232));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(24, 26, 28));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dotum", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 162, 232));
        jLabel2.setText("FULLNAME");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 80, 20));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 590, 10));

        jLabel3.setFont(new java.awt.Font("Dotum", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 162, 232));
        jLabel3.setText("PHONE NUMBER");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 590, 10));

        jLabel4.setFont(new java.awt.Font("Dotum", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 162, 232));
        jLabel4.setText("ADDRESS");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 590, 10));

        jLabel5.setFont(new java.awt.Font("Dotum", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 162, 232));
        jLabel5.setText("NEXT OF KIN");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 590, 10));

        jLabel6.setFont(new java.awt.Font("Dotum", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 162, 232));
        jLabel6.setText("PHONE NUMBER OF NEXT OF KIN");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 230, 20));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 590, 10));

        Nextbtn.setBackground(new java.awt.Color(0, 162, 232));
        Nextbtn.setFont(new java.awt.Font("Dotum", 1, 12)); // NOI18N
        Nextbtn.setForeground(new java.awt.Color(255, 255, 255));
        Nextbtn.setText("Next");
        Nextbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Nextbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 411, 70, 30));

        Cancelbtn.setBackground(new java.awt.Color(0, 162, 232));
        Cancelbtn.setFont(new java.awt.Font("Dotum", 1, 12)); // NOI18N
        Cancelbtn.setForeground(new java.awt.Color(255, 255, 255));
        Cancelbtn.setText("Cancel");
        Cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 410, -1, -1));

        phone_no.setBackground(new java.awt.Color(24, 26, 28));
        phone_no.setFont(new java.awt.Font("Dotum", 1, 14)); // NOI18N
        phone_no.setForeground(new java.awt.Color(255, 255, 255));
        phone_no.setBorder(null);
        jPanel2.add(phone_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 420, 40));

        kinNo.setBackground(new java.awt.Color(24, 26, 28));
        kinNo.setFont(new java.awt.Font("Dotum", 1, 14)); // NOI18N
        kinNo.setForeground(new java.awt.Color(255, 255, 255));
        kinNo.setBorder(null);
        jPanel2.add(kinNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 460, 40));

        fullname.setBackground(new java.awt.Color(24, 26, 28));
        fullname.setFont(new java.awt.Font("Dotum", 1, 14)); // NOI18N
        fullname.setForeground(new java.awt.Color(255, 255, 255));
        fullname.setBorder(null);
        fullname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fullnameFocusGained(evt);
            }
        });
        jPanel2.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 560, 40));

        address.setBackground(new java.awt.Color(24, 26, 28));
        address.setFont(new java.awt.Font("Dotum", 1, 14)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setBorder(null);
        jPanel2.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 560, 40));

        kin.setBackground(new java.awt.Color(24, 26, 28));
        kin.setFont(new java.awt.Font("Dotum", 1, 14)); // NOI18N
        kin.setForeground(new java.awt.Color(255, 255, 255));
        kin.setBorder(null);
        jPanel2.add(kin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 560, 40));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(24, 26, 28));
        jTextField1.setFont(new java.awt.Font("Dotum", 2, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("(08*********)");
        jTextField1.setBorder(null);
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 100, 30));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(24, 26, 28));
        jTextField2.setFont(new java.awt.Font("Dotum", 2, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("(08*********)");
        jTextField2.setBorder(null);
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 100, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 670, 470));

        jLabel1.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(24, 26, 28));
        jLabel1.setText("1/4   Register");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextbtnActionPerformed
       
         String name=fullname.getText();
        String num=phone_no.getText();
        
        String Address=address.getText();
        String nextkin=kin.getText();
        String nextkinNo=kinNo.getText();
        
       
       
    try {
        if((numberValidation(num))&&(numberValidation(nextkinNo))){
            
            
             
              try{
//            String sql="insert into REGISTER(NAME,PHONE_NO,ADDRESS,KIN_NAME,KIN_NO)values(?,?,?,?,?)";
//            pst=conn.prepareStatement(sql);
//            pst.setString(1, name);
//            pst.setString(2, num);
//            pst.setString(3, Address);
//            pst.setString(4, nextkin);
//            pst.setString(5, nextkinNo);
//            pst.execute();
            
             Bookings book=new Bookings(name,num,Address,nextkin,nextkinNo,this);
             
             book.setLocationRelativeTo(null);
             book.setVisible(true);
             this.setVisible(false);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
             
        }else {
            if(!numberValidation(num))
            JOptionPane.showMessageDialog(null, "Invalid Phone number");
            if(!numberValidation(nextkinNo))
            JOptionPane.showMessageDialog(null, "Invalid Next of kin number");
    }
    }catch(StringIndexOutOfBoundsException e){
        JOptionPane.showMessageDialog(null, "Please fill all fields");
        
    }    
        
       
    }//GEN-LAST:event_NextbtnActionPerformed

    
    private void CancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbtnActionPerformed
        // TODO add your handling code here:
      Home Home=new Home();
     Home.setLocationRelativeTo(null);
     Home.setVisible(true);
    
      this.setVisible(false);
    }//GEN-LAST:event_CancelbtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     //  err.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void fullnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fullnameFocusGained
      
    }//GEN-LAST:event_fullnameFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelbtn;
    private javax.swing.JButton Nextbtn;
    private javax.swing.JTextField address;
    private javax.swing.JTextField fullname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField kin;
    private javax.swing.JTextField kinNo;
    private javax.swing.JTextField phone_no;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("akmaicon.png")));
    }
}
